services:
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: pong_backend
    ports:
      - "3333:3333"
    volumes:
      - ./Back:/app
      - /app/node_modules
      - ./Back/data:/app/data
    environment:
      - PORT=3333
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - pong-network
    command: npm run dev

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
      args:
        - FRONT_PORT=${FRONT_PORT:-5173}
    container_name: pong_frontend
    volumes:
      - ./Front:/app
      - /app/node_modules
    ports:
      - "${FRONT_PORT:-5173}:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://${HOST_IP}::3333
    env_file:
      - .env
    networks:
      - pong-network
    command: sh -c "npm run css & npm run dev -- --host"
    depends_on:
      - backend

networks:
  pong-network:
    driver: bridge
